name: example_cd
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  example_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter Runner
        uses: jddeep/Flutter-Runner@1.2.0
    
