name: Android Release


on:
  
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

permissions:
  contents: write
  

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.11"
          channel: 'stable'
      # 12
      - name: Get dependencies
        run: flutter pub get -v

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk --release
      
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: Release        
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: build/app/outputs/flutter-apk/app-release.apk
